# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09029c83a022174287bae2177d11c54c6d2b2227ededefc928c1bb2a75241fc4bef26f9b23f46c973de1cbca5b8b188b8d30084970fb01c0cde50a86efcaac86

test:
  secret_key_base: 06bc54a9eb2ac97425c183a24643b7b8c599f7736a3d4e22edfeb7a9d846689aaad1b7159f76f0311991e1ee8bb378c156b4bb1c472d39d585ff38a29c562843

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
